[package]
name = "agave-xdp"
description = "Agave XDP implementation"
version = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = true

[features]
agave-unstable-api = []

[dependencies]
crossbeam-channel = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
caps = { workspace = true }
