[package]
name = "solana-svm-type-overrides"
description = "Type overrides for specialized testing"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []
shuttle-test = ["dep:shuttle"]
executor = ["dep:futures"]

[dependencies]
futures = { workspace = true, optional = true }
rand = { workspace = true }
shuttle = { workspace = true, optional = true }
