[package]
name = "solana-lattice-hash"
description = "Solana Lattice Hash"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
agave-unstable-api = []

[dependencies]
base64 = { workspace = true }
blake3 = { workspace = true }
bs58 = { workspace = true }
bytemuck = { workspace = true, features = ["must_cast"] }

[dev-dependencies]
criterion = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
solana-lattice-hash = { path = ".", features = ["agave-unstable-api"] }

[[bench]]
name = "bench_lt_hash"
harness = false
