[package]
name = "solana-sbf-rust-curve25519"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-curve25519 = { workspace = true, features = ["agave-unstable-api"] }
solana-msg = { workspace = true }
solana-program-entrypoint = { workspace = true }

[lints]
workspace = true
