[package]
name = "agave-syscalls"
description = "Agave implementation of the Solana syscalls."
documentation = "https://docs.rs/agave-syscalls"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["metrics"]
agave-unstable-api = []
metrics = ["solana-program-runtime/metrics"]
shuttle-test = [
    "solana-program-runtime/shuttle-test",
    "solana-sbpf/shuttle-test",
    "solana-svm-type-overrides/shuttle-test",
]
svm-internal = []

[dependencies]
bincode = { workspace = true }
libsecp256k1 = { workspace = true }
num-traits = { workspace = true }
solana-account = { workspace = true }
solana-account-info = { workspace = true }
solana-big-mod-exp = { workspace = true }
solana-blake3-hasher = { workspace = true, features = ["blake3"] }
solana-bn254 = { workspace = true }
solana-clock = { workspace = true }
solana-cpi = { workspace = true }
solana-curve25519 = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-keccak-hasher = { workspace = true, features = ["sha3"] }
solana-loader-v3-interface = { workspace = true, features = ["serde"] }
solana-poseidon = { workspace = true }
solana-program-entrypoint = { workspace = true }
solana-program-runtime = { workspace = true }
solana-pubkey = { workspace = true }
solana-sbpf = { workspace = true, features = ["jit"] }
solana-sdk-ids = { workspace = true }
solana-secp256k1-recover = { workspace = true }
solana-sha256-hasher = { workspace = true }
solana-stable-layout = { workspace = true }
solana-stake-interface = { workspace = true }
solana-svm-callback = { workspace = true }
solana-svm-feature-set = { workspace = true }
solana-svm-log-collector = { workspace = true }
solana-svm-measure = { workspace = true }
solana-svm-timings = { workspace = true }
solana-svm-type-overrides = { workspace = true }
solana-sysvar = { workspace = true }
solana-sysvar-id = { workspace = true }
solana-transaction-context = { workspace = true, features = ["bincode"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
solana-epoch-rewards = { workspace = true }
solana-epoch-schedule = { workspace = true }
solana-fee-calculator = { workspace = true }
solana-last-restart-slot = { workspace = true }
solana-program = { workspace = true }
solana-program-runtime = { workspace = true, features = ["dev-context-only-utils"] }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-rent = { workspace = true }
solana-slot-hashes = { workspace = true }
solana-transaction-context = { workspace = true, features = ["dev-context-only-utils"] }
static_assertions = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
