[package]
name = "solana-transaction-status"
description = "Solana transaction status types"
documentation = "https://docs.rs/solana-transaction-status"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
agave-unstable-api = []

[dependencies]
Inflector = { workspace = true }
agave-reserved-account-keys = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder = { workspace = true }
solana-address-lookup-table-interface = { workspace = true }
solana-clock = { workspace = true }
solana-hash = { workspace = true }
solana-instruction = { workspace = true }
solana-loader-v2-interface = { workspace = true, features = ["bincode"] }
solana-loader-v3-interface = { workspace = true, features = ["bincode"] }
solana-message = { workspace = true }
solana-program-option = { workspace = true }
solana-pubkey = { workspace = true }
solana-reward-info = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-signature = { workspace = true }
solana-stake-interface = { workspace = true }
solana-system-interface = { workspace = true }
solana-transaction = { workspace = true }
solana-transaction-error = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solana-vote-interface = { workspace = true }
spl-associated-token-account-interface = { workspace = true, features = ["borsh"] }
spl-memo-interface = { workspace = true }
spl-token-2022-interface = { workspace = true }
spl-token-group-interface = { workspace = true }
spl-token-interface = { workspace = true }
spl-token-metadata-interface = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bencher = { workspace = true }
bytemuck = { workspace = true }
solana-pubkey = { workspace = true, features = ["rand"] }
solana-transaction-status = { path = ".", features = ["agave-unstable-api"] }
spl-token-confidential-transfer-proof-extraction = { workspace = true }

[[bench]]
name = "extract_memos"
harness = false
