[package]
name = "solana-svm-timings"
description = "Solana Execution Timings"
documentation = "https://docs.rs/solana-svm-timings"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
agave-unstable-api = []

[dependencies]
eager = { workspace = true }
enum-iterator = { workspace = true }
solana-pubkey = { workspace = true }
